//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contato_Vinculo
    {
        public int IDContatoVinculo { get; set; }
        public Nullable<int> IDTipoContato { get; set; }
        public Nullable<int> IDPessoa { get; set; }
        public string Descricao { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        public virtual Tipo_Contato Tipo_Contato { get; set; }
    }
}
