//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Frete4UEntities : DbContext
    {
        public Frete4UEntities()
            : base("name=Frete4UEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Contato_Vinculo> Contato_Vinculo { get; set; }
        public virtual DbSet<Fabricante_Veiculo> Fabricante_Veiculo { get; set; }
        public virtual DbSet<Pessoa> Pessoa { get; set; }
        public virtual DbSet<Pessoa_Veiculo_Vinculo> Pessoa_Veiculo_Vinculo { get; set; }
        public virtual DbSet<Solicitacao> Solicitacao { get; set; }
        public virtual DbSet<Tipo_Combustivel> Tipo_Combustivel { get; set; }
        public virtual DbSet<Tipo_Contato> Tipo_Contato { get; set; }
        public virtual DbSet<Tipo_Pessoa> Tipo_Pessoa { get; set; }
        public virtual DbSet<Tipo_Veiculo> Tipo_Veiculo { get; set; }
        public virtual DbSet<Veiculo> Veiculo { get; set; }
    }
}
