//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pessoa
    {
        public Pessoa()
        {
            this.Contato_Vinculo = new HashSet<Contato_Vinculo>();
            this.Pessoa_Veiculo_Vinculo = new HashSet<Pessoa_Veiculo_Vinculo>();
            this.Solicitacao = new HashSet<Solicitacao>();
        }
    
        public int IDPessoa { get; set; }
        public Nullable<int> IDTipoPessoa { get; set; }
        public string Nome { get; set; }
        public string CPF { get; set; }
        public string CNPJ { get; set; }
        public string Logradouro { get; set; }
        public string NumeroEndereco { get; set; }
        public string Bairro { get; set; }
        public string Complemento { get; set; }
        public string Cidade { get; set; }
        public string Estado { get; set; }
        public Nullable<bool> Inativo { get; set; }
    
        public virtual ICollection<Contato_Vinculo> Contato_Vinculo { get; set; }
        public virtual ICollection<Pessoa_Veiculo_Vinculo> Pessoa_Veiculo_Vinculo { get; set; }
        public virtual ICollection<Solicitacao> Solicitacao { get; set; }
        public virtual Tipo_Pessoa Tipo_Pessoa { get; set; }
    }
}
