//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitacao
    {
        public int IDPessoa { get; set; }
        public int IDSolicitacao { get; set; }
        public Nullable<System.DateTime> DataHora { get; set; }
        public Nullable<bool> Finalizado { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
    }
}
