//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Veiculo
    {
        public Tipo_Veiculo()
        {
            this.Veiculo = new HashSet<Veiculo>();
        }
    
        public int IDTipoVeiculo { get; set; }
        public string Descricao { get; set; }
        public Nullable<bool> Inativo { get; set; }
    
        public virtual ICollection<Veiculo> Veiculo { get; set; }
    }
}
