//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestPage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tipo_Contato
    {
        public Tipo_Contato()
        {
            this.Contato_Vinculo = new HashSet<Contato_Vinculo>();
        }
    
        public int IDTipoContato { get; set; }
        public string Descricao { get; set; }
        public Nullable<bool> Inativo { get; set; }
    
        public virtual ICollection<Contato_Vinculo> Contato_Vinculo { get; set; }
    }
}
